### ISSUE TITLE
Firebase firebase_app_id_file 

### ISSUE THREAD

**Issue by OwnappIos** [AngeloAvv/flutter_flavorizr#164]
How can I create this firebase_app_id_file json file based on my different flavour?
I used firebase CLI to configure firebase_option file but not sure this iOS file how to handle it.

**Comment by AngeloAvv** [comment]
Hello @OwnappIos , if you use flutter_flavorizr you need to stick with the previous version of the Firebase instructions to set up your project. Flutter_flavorizr is incompatible with firebase CLI.

Instead of running the CLI you need to manually download the firebase files from the console and place them in the right places, then flutter_flavorizr will do the rest for you. Just remember to initialize your firebase app in the main.dart file
