### ISSUE TITLE
Platform Optional

### ISSUE THREAD

**Issue by LinHaoLove** [AngeloAvv/flutter_flavorizr#181]
First of all, being able to support macos and windows is a great update.

I have projects that support iOS and Android. And projects that support iOS and Android and macOS and Windows.

When I used 2.2.0 on project that support iOS and Android.
Macos seemed to be a must, and I couldn't find the instructions in the relevant documentation.

`
Error reading from macos/Runner/Info.plist. The file does not exist
`

**Comment by blueeyestw** [comment]
Same issue here. I'm only using iOS and Android but it seems macOS is a requirement?

**Comment by GruppeGAM** [comment]
Same here. I want to use only IOS and Android. Unfortunately, I haven't found a way to prevent it from checking if the directory exists when initializing the processor, because the processor always loads all **AbstractProcessor** first in the **_initAvailableProcessors** static function.

By the way, thanks for your great work.
