### ISSUE TITLE
error while building ios, bitcode is not disabled

### ISSUE THREAD

**Issue by danielwalczak** [AngeloAvv/flutter_flavorizr#28]
I think because those lines were removed from podfile after I run flavorizr, its not longer working properly

```
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
```
error
```
prod-iphoneos/DKImagePickerController/DKImagePickerController.framework/DKImagePickerController' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode
    setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/midiflow/workspace/mobile/build/ios/Debug
    prod-iphoneos/DKImagePickerController/DKImagePickerController.framework/DKImagePickerController' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

I have too disable bitcode manually for each schema

**Comment by AngeloAvv** [comment]
I created the creation schema script (see add_build_configuration.rb) based on the default XCode schema. It seems that you flavorized an existing project, and I wouldn't do that operation, as it could be potentially distructive. Anyway, we could think of a configuration entry to add in the existing pubspec under the iOS (or single flavor) branch in order to allow the user to customize these settings. What do you think about it?

**Comment by danielwalczak** [comment]
Yes I added to existing project right after I upgraded from 1.17 flutter to 1.24. I think its good idea to have this option, many people will consider adding flavors into existing projects.

**Comment by AngeloAvv** [comment]
Hi @danielwalczak , with the latest release (v1.0.8) you could define a set of platform specific and/or flavor specific build settings. Can you give it a try?

**Comment by danielwalczak** [comment]
Yeah I will, I think most of the issues I experiences was due to xcode 12 and flutter 1.20.4.

We can close this one for now.
